set_directive_pipeline encode/encode_label0
set_directive_pipeline decode/decode_label2
set_directive_pipeline decode/decode_label3
set_directive_pipeline reset/reset_label4
set_directive_pipeline reset/reset_label6
set_directive_pipeline filtez/filtez_label8
set_directive_pipeline quantl/quantl_label9
set_directive_unroll encode/encode_label0 -factor 4
set_directive_unroll encode/encode_label1 -factor 4
set_directive_unroll decode/decode_label2 -factor 2
set_directive_unroll decode/decode_label3 -factor 4
set_directive_unroll reset/reset_label5 -factor 2
set_directive_unroll reset/reset_label6 -factor 2
set_directive_unroll upzero/upzero_label11 -factor 4
set_directive_unroll adpcm_main/adpcm_main_label12 -factor 8
set_directive_unroll adpcm_main/adpcm_main_label13 -factor 2
set_directive_loop_merge reset
