// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sha_transform.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sha_transform::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sha_transform::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<19> sha_transform::ap_ST_fsm_state1 = "1";
const sc_lv<19> sha_transform::ap_ST_fsm_state2 = "10";
const sc_lv<19> sha_transform::ap_ST_fsm_state3 = "100";
const sc_lv<19> sha_transform::ap_ST_fsm_state4 = "1000";
const sc_lv<19> sha_transform::ap_ST_fsm_state5 = "10000";
const sc_lv<19> sha_transform::ap_ST_fsm_state6 = "100000";
const sc_lv<19> sha_transform::ap_ST_fsm_state7 = "1000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state8 = "10000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state9 = "100000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state10 = "1000000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state11 = "10000000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state12 = "100000000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<19> sha_transform::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<32> sha_transform::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> sha_transform::ap_const_lv32_1 = "1";
const sc_lv<1> sha_transform::ap_const_lv1_0 = "0";
const sc_lv<32> sha_transform::ap_const_lv32_3 = "11";
const sc_lv<32> sha_transform::ap_const_lv32_4 = "100";
const sc_lv<32> sha_transform::ap_const_lv32_5 = "101";
const sc_lv<32> sha_transform::ap_const_lv32_6 = "110";
const sc_lv<32> sha_transform::ap_const_lv32_7 = "111";
const sc_lv<32> sha_transform::ap_const_lv32_8 = "1000";
const sc_lv<32> sha_transform::ap_const_lv32_9 = "1001";
const sc_lv<32> sha_transform::ap_const_lv32_A = "1010";
const sc_lv<32> sha_transform::ap_const_lv32_B = "1011";
const sc_lv<32> sha_transform::ap_const_lv32_C = "1100";
const sc_lv<32> sha_transform::ap_const_lv32_D = "1101";
const sc_lv<32> sha_transform::ap_const_lv32_E = "1110";
const sc_lv<32> sha_transform::ap_const_lv32_F = "1111";
const sc_lv<1> sha_transform::ap_const_lv1_1 = "1";
const sc_lv<32> sha_transform::ap_const_lv32_10 = "10000";
const sc_lv<32> sha_transform::ap_const_lv32_11 = "10001";
const sc_lv<5> sha_transform::ap_const_lv5_0 = "00000";
const sc_lv<32> sha_transform::ap_const_lv32_2 = "10";
const sc_lv<7> sha_transform::ap_const_lv7_10 = "10000";
const sc_lv<6> sha_transform::ap_const_lv6_14 = "10100";
const sc_lv<6> sha_transform::ap_const_lv6_28 = "101000";
const sc_lv<7> sha_transform::ap_const_lv7_3C = "111100";
const sc_lv<3> sha_transform::ap_const_lv3_0 = "000";
const sc_lv<3> sha_transform::ap_const_lv3_1 = "1";
const sc_lv<3> sha_transform::ap_const_lv3_2 = "10";
const sc_lv<3> sha_transform::ap_const_lv3_3 = "11";
const sc_lv<3> sha_transform::ap_const_lv3_4 = "100";
const sc_lv<32> sha_transform::ap_const_lv32_12 = "10010";
const sc_lv<5> sha_transform::ap_const_lv5_10 = "10000";
const sc_lv<5> sha_transform::ap_const_lv5_1 = "1";
const sc_lv<7> sha_transform::ap_const_lv7_50 = "1010000";
const sc_lv<7> sha_transform::ap_const_lv7_7D = "1111101";
const sc_lv<7> sha_transform::ap_const_lv7_78 = "1111000";
const sc_lv<7> sha_transform::ap_const_lv7_72 = "1110010";
const sc_lv<7> sha_transform::ap_const_lv7_70 = "1110000";
const sc_lv<7> sha_transform::ap_const_lv7_1 = "1";
const sc_lv<5> sha_transform::ap_const_lv5_14 = "10100";
const sc_lv<32> sha_transform::ap_const_lv32_1B = "11011";
const sc_lv<32> sha_transform::ap_const_lv32_1F = "11111";
const sc_lv<32> sha_transform::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> sha_transform::ap_const_lv32_5A827999 = "1011010100000100111100110011001";
const sc_lv<6> sha_transform::ap_const_lv6_1 = "1";
const sc_lv<32> sha_transform::ap_const_lv32_6ED9EBA1 = "1101110110110011110101110100001";
const sc_lv<6> sha_transform::ap_const_lv6_3C = "111100";
const sc_lv<32> sha_transform::ap_const_lv32_8F1BBCDC = "10001111000110111011110011011100";
const sc_lv<32> sha_transform::ap_const_lv32_CA62C1D6 = "11001010011000101100000111010110";
const bool sha_transform::ap_const_boolean_1 = true;

sha_transform::sha_transform(sc_module_name name) : sc_module(name), mVcdFile(0) {
    W_U = new sha_transform_W("W_U");
    W_U->clk(ap_clk);
    W_U->reset(ap_rst);
    W_U->address0(W_address0);
    W_U->ce0(W_ce0);
    W_U->we0(W_we0);
    W_U->d0(sha_info_data_q0);
    W_U->q0(W_q0);
    W_U->address1(W_address1);
    W_U->ce1(W_ce1);
    W_U->we1(W_we1);
    W_U->d1(W_d1);
    W_U->q1(W_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_C_1_fu_685_p3);
    sensitive << ( trunc_ln117_1_fu_671_p1 );
    sensitive << ( lshr_ln117_1_fu_675_p4 );

    SC_METHOD(thread_C_2_fu_782_p3);
    sensitive << ( trunc_ln121_1_fu_768_p1 );
    sensitive << ( lshr_ln121_1_fu_772_p4 );

    SC_METHOD(thread_C_3_fu_891_p3);
    sensitive << ( trunc_ln125_1_fu_877_p1 );
    sensitive << ( lshr_ln125_1_fu_881_p4 );

    SC_METHOD(thread_C_4_fu_970_p3);
    sensitive << ( trunc_ln129_1_fu_956_p1 );
    sensitive << ( lshr_ln129_1_fu_960_p4 );

    SC_METHOD(thread_W_address0);
    sensitive << ( zext_ln103_reg_1030 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln107_fu_518_p1 );
    sensitive << ( zext_ln107_3_fu_551_p1 );
    sensitive << ( zext_ln117_fu_596_p1 );
    sensitive << ( zext_ln125_fu_796_p1 );

    SC_METHOD(thread_W_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( zext_ln107_1_fu_529_p1 );
    sensitive << ( zext_ln107_2_fu_540_p1 );
    sensitive << ( zext_ln107_4_fu_573_p1 );
    sensitive << ( zext_ln121_fu_699_p1 );
    sensitive << ( zext_ln129_fu_939_p1 );

    SC_METHOD(thread_W_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_W_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_W_d1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( xor_ln107_1_fu_560_p2 );
    sensitive << ( xor_ln107_fu_556_p2 );

    SC_METHOD(thread_W_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_W_we1);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_add_ln107_1_fu_523_p2);
    sensitive << ( i_1_reg_207 );

    SC_METHOD(thread_add_ln107_2_fu_534_p2);
    sensitive << ( i_1_reg_207 );

    SC_METHOD(thread_add_ln107_3_fu_545_p2);
    sensitive << ( i_1_reg_207 );

    SC_METHOD(thread_add_ln107_fu_512_p2);
    sensitive << ( i_1_reg_207 );

    SC_METHOD(thread_add_ln117_1_fu_653_p2);
    sensitive << ( or_ln_fu_615_p3 );

    SC_METHOD(thread_add_ln117_2_fu_659_p2);
    sensitive << ( add_ln117_1_fu_653_p2 );
    sensitive << ( or_ln117_fu_641_p2 );

    SC_METHOD(thread_add_ln117_fu_647_p2);
    sensitive << ( W_q0 );
    sensitive << ( E_0_reg_219 );

    SC_METHOD(thread_add_ln121_1_fu_750_p2);
    sensitive << ( or_ln1_fu_724_p3 );

    SC_METHOD(thread_add_ln121_2_fu_756_p2);
    sensitive << ( add_ln121_1_fu_750_p2 );
    sensitive << ( xor_ln121_1_fu_738_p2 );

    SC_METHOD(thread_add_ln121_fu_744_p2);
    sensitive << ( W_q1 );
    sensitive << ( E_1_reg_283 );

    SC_METHOD(thread_add_ln125_1_fu_859_p2);
    sensitive << ( or_ln125_1_fu_847_p2 );
    sensitive << ( or_ln2_fu_821_p3 );

    SC_METHOD(thread_add_ln125_2_fu_865_p2);
    sensitive << ( add_ln125_1_fu_859_p2 );

    SC_METHOD(thread_add_ln125_fu_853_p2);
    sensitive << ( W_q0 );
    sensitive << ( E_2_reg_352 );

    SC_METHOD(thread_add_ln129_1_fu_944_p2);
    sensitive << ( or_ln3_fu_919_p3 );

    SC_METHOD(thread_add_ln129_2_fu_950_p2);
    sensitive << ( add_ln129_1_fu_944_p2 );
    sensitive << ( xor_ln129_1_fu_933_p2 );

    SC_METHOD(thread_add_ln129_fu_1006_p2);
    sensitive << ( W_q1 );
    sensitive << ( E_3_reg_421 );

    SC_METHOD(thread_add_ln132_fu_984_p2);
    sensitive << ( A_reg_1078 );
    sensitive << ( B_7_reg_466 );

    SC_METHOD(thread_add_ln133_fu_990_p2);
    sensitive << ( B_reg_1084 );
    sensitive << ( B_3_reg_456 );

    SC_METHOD(thread_add_ln134_fu_996_p2);
    sensitive << ( C_reg_1090 );
    sensitive << ( D_4_reg_444 );

    SC_METHOD(thread_add_ln135_fu_1001_p2);
    sensitive << ( D_reg_1096 );
    sensitive << ( E_7_reg_432 );

    SC_METHOD(thread_add_ln136_fu_1017_p2);
    sensitive << ( E_reg_1102 );
    sensitive << ( E_3_reg_421 );

    SC_METHOD(thread_and_ln117_1_fu_635_p2);
    sensitive << ( E_4_reg_229 );
    sensitive << ( xor_ln117_fu_629_p2 );

    SC_METHOD(thread_and_ln117_fu_623_p2);
    sensitive << ( D_1_reg_240 );
    sensitive << ( B_0_reg_251 );

    SC_METHOD(thread_and_ln125_1_fu_841_p2);
    sensitive << ( E_6_reg_363 );
    sensitive << ( D_3_reg_375 );

    SC_METHOD(thread_and_ln125_fu_835_p2);
    sensitive << ( B_2_reg_387 );
    sensitive << ( or_ln125_fu_829_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_i_10_fu_978_p2);
    sensitive << ( i_5_reg_478 );

    SC_METHOD(thread_i_6_fu_578_p2);
    sensitive << ( i_1_reg_207 );

    SC_METHOD(thread_i_7_fu_590_p2);
    sensitive << ( i_2_reg_272 );

    SC_METHOD(thread_i_8_fu_704_p2);
    sensitive << ( i_3_reg_341 );

    SC_METHOD(thread_i_9_fu_801_p2);
    sensitive << ( i_4_reg_410 );

    SC_METHOD(thread_i_fu_495_p2);
    sensitive << ( i_0_reg_196 );

    SC_METHOD(thread_icmp_ln101_fu_489_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_196 );

    SC_METHOD(thread_icmp_ln105_fu_506_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i_1_reg_207 );

    SC_METHOD(thread_icmp_ln115_fu_584_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( i_2_reg_272 );

    SC_METHOD(thread_icmp_ln119_fu_693_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( i_3_reg_341 );

    SC_METHOD(thread_icmp_ln123_fu_790_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( i_4_reg_410 );

    SC_METHOD(thread_icmp_ln127_fu_899_p2);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( i_5_reg_478 );

    SC_METHOD(thread_lshr_ln117_1_fu_675_p4);
    sensitive << ( B_0_reg_251 );

    SC_METHOD(thread_lshr_ln121_1_fu_772_p4);
    sensitive << ( B_1_reg_318 );

    SC_METHOD(thread_lshr_ln125_1_fu_881_p4);
    sensitive << ( B_2_reg_387 );

    SC_METHOD(thread_lshr_ln129_1_fu_960_p4);
    sensitive << ( B_3_reg_456 );

    SC_METHOD(thread_lshr_ln1_fu_714_p4);
    sensitive << ( B_5_reg_329 );

    SC_METHOD(thread_lshr_ln2_fu_811_p4);
    sensitive << ( B_6_reg_398 );

    SC_METHOD(thread_lshr_ln3_fu_909_p4);
    sensitive << ( B_7_reg_466 );

    SC_METHOD(thread_lshr_ln_fu_605_p4);
    sensitive << ( B_4_reg_261 );

    SC_METHOD(thread_or_ln117_fu_641_p2);
    sensitive << ( and_ln117_fu_623_p2 );
    sensitive << ( and_ln117_1_fu_635_p2 );

    SC_METHOD(thread_or_ln125_1_fu_847_p2);
    sensitive << ( and_ln125_fu_835_p2 );
    sensitive << ( and_ln125_1_fu_841_p2 );

    SC_METHOD(thread_or_ln125_fu_829_p2);
    sensitive << ( E_6_reg_363 );
    sensitive << ( D_3_reg_375 );

    SC_METHOD(thread_or_ln1_fu_724_p3);
    sensitive << ( trunc_ln121_fu_710_p1 );
    sensitive << ( lshr_ln1_fu_714_p4 );

    SC_METHOD(thread_or_ln2_fu_821_p3);
    sensitive << ( trunc_ln125_fu_807_p1 );
    sensitive << ( lshr_ln2_fu_811_p4 );

    SC_METHOD(thread_or_ln3_fu_919_p3);
    sensitive << ( trunc_ln129_fu_905_p1 );
    sensitive << ( lshr_ln3_fu_909_p4 );

    SC_METHOD(thread_or_ln_fu_615_p3);
    sensitive << ( trunc_ln117_fu_601_p1 );
    sensitive << ( lshr_ln_fu_605_p4 );

    SC_METHOD(thread_sha_info_data_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln103_fu_501_p1 );

    SC_METHOD(thread_sha_info_data_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sha_info_digest_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_sha_info_digest_address1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_sha_info_digest_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_sha_info_digest_ce1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_sha_info_digest_d0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( add_ln135_reg_1205 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( add_ln133_fu_990_p2 );

    SC_METHOD(thread_sha_info_digest_d1);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( add_ln134_reg_1200 );
    sensitive << ( add_ln136_reg_1215 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( add_ln132_fu_984_p2 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_sha_info_digest_we0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( icmp_ln127_fu_899_p2 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_sha_info_digest_we1);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( icmp_ln127_fu_899_p2 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_temp_1_fu_762_p2);
    sensitive << ( add_ln121_2_fu_756_p2 );
    sensitive << ( add_ln121_fu_744_p2 );

    SC_METHOD(thread_temp_2_fu_871_p2);
    sensitive << ( add_ln125_2_fu_865_p2 );
    sensitive << ( add_ln125_fu_853_p2 );

    SC_METHOD(thread_temp_3_fu_1012_p2);
    sensitive << ( add_ln129_2_reg_1185 );
    sensitive << ( add_ln129_fu_1006_p2 );

    SC_METHOD(thread_temp_fu_665_p2);
    sensitive << ( add_ln117_2_fu_659_p2 );
    sensitive << ( add_ln117_fu_647_p2 );

    SC_METHOD(thread_trunc_ln117_1_fu_671_p1);
    sensitive << ( B_0_reg_251 );

    SC_METHOD(thread_trunc_ln117_fu_601_p1);
    sensitive << ( B_4_reg_261 );

    SC_METHOD(thread_trunc_ln121_1_fu_768_p1);
    sensitive << ( B_1_reg_318 );

    SC_METHOD(thread_trunc_ln121_fu_710_p1);
    sensitive << ( B_5_reg_329 );

    SC_METHOD(thread_trunc_ln125_1_fu_877_p1);
    sensitive << ( B_2_reg_387 );

    SC_METHOD(thread_trunc_ln125_fu_807_p1);
    sensitive << ( B_6_reg_398 );

    SC_METHOD(thread_trunc_ln129_1_fu_956_p1);
    sensitive << ( B_3_reg_456 );

    SC_METHOD(thread_trunc_ln129_fu_905_p1);
    sensitive << ( B_7_reg_466 );

    SC_METHOD(thread_xor_ln107_1_fu_560_p2);
    sensitive << ( W_q0 );
    sensitive << ( W_q1 );

    SC_METHOD(thread_xor_ln107_fu_556_p2);
    sensitive << ( W_load_reg_1053 );
    sensitive << ( W_load_1_reg_1058 );

    SC_METHOD(thread_xor_ln117_fu_629_p2);
    sensitive << ( B_0_reg_251 );

    SC_METHOD(thread_xor_ln121_1_fu_738_p2);
    sensitive << ( D_2_reg_306 );
    sensitive << ( xor_ln121_fu_732_p2 );

    SC_METHOD(thread_xor_ln121_fu_732_p2);
    sensitive << ( E_5_reg_294 );
    sensitive << ( B_1_reg_318 );

    SC_METHOD(thread_xor_ln129_1_fu_933_p2);
    sensitive << ( D_4_reg_444 );
    sensitive << ( xor_ln129_fu_927_p2 );

    SC_METHOD(thread_xor_ln129_fu_927_p2);
    sensitive << ( E_7_reg_432 );
    sensitive << ( B_3_reg_456 );

    SC_METHOD(thread_zext_ln103_fu_501_p1);
    sensitive << ( i_0_reg_196 );

    SC_METHOD(thread_zext_ln107_1_fu_529_p1);
    sensitive << ( add_ln107_1_fu_523_p2 );

    SC_METHOD(thread_zext_ln107_2_fu_540_p1);
    sensitive << ( add_ln107_2_fu_534_p2 );

    SC_METHOD(thread_zext_ln107_3_fu_551_p1);
    sensitive << ( add_ln107_3_fu_545_p2 );

    SC_METHOD(thread_zext_ln107_4_fu_573_p1);
    sensitive << ( i_1_reg_207 );

    SC_METHOD(thread_zext_ln107_fu_518_p1);
    sensitive << ( add_ln107_fu_512_p2 );

    SC_METHOD(thread_zext_ln117_fu_596_p1);
    sensitive << ( i_2_reg_272 );

    SC_METHOD(thread_zext_ln121_fu_699_p1);
    sensitive << ( i_3_reg_341 );

    SC_METHOD(thread_zext_ln125_fu_796_p1);
    sensitive << ( i_4_reg_410 );

    SC_METHOD(thread_zext_ln129_fu_939_p1);
    sensitive << ( i_5_reg_478 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln101_fu_489_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln105_fu_506_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln115_fu_584_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( icmp_ln119_fu_693_p2 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( icmp_ln123_fu_790_p2 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( icmp_ln127_fu_899_p2 );

    ap_CS_fsm = "0000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sha_transform_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, sha_info_data_address0, "(port)sha_info_data_address0");
    sc_trace(mVcdFile, sha_info_data_ce0, "(port)sha_info_data_ce0");
    sc_trace(mVcdFile, sha_info_data_q0, "(port)sha_info_data_q0");
    sc_trace(mVcdFile, sha_info_digest_address0, "(port)sha_info_digest_address0");
    sc_trace(mVcdFile, sha_info_digest_ce0, "(port)sha_info_digest_ce0");
    sc_trace(mVcdFile, sha_info_digest_we0, "(port)sha_info_digest_we0");
    sc_trace(mVcdFile, sha_info_digest_d0, "(port)sha_info_digest_d0");
    sc_trace(mVcdFile, sha_info_digest_q0, "(port)sha_info_digest_q0");
    sc_trace(mVcdFile, sha_info_digest_address1, "(port)sha_info_digest_address1");
    sc_trace(mVcdFile, sha_info_digest_ce1, "(port)sha_info_digest_ce1");
    sc_trace(mVcdFile, sha_info_digest_we1, "(port)sha_info_digest_we1");
    sc_trace(mVcdFile, sha_info_digest_d1, "(port)sha_info_digest_d1");
    sc_trace(mVcdFile, sha_info_digest_q1, "(port)sha_info_digest_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_495_p2, "i_fu_495_p2");
    sc_trace(mVcdFile, i_reg_1025, "i_reg_1025");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln103_fu_501_p1, "zext_ln103_fu_501_p1");
    sc_trace(mVcdFile, zext_ln103_reg_1030, "zext_ln103_reg_1030");
    sc_trace(mVcdFile, icmp_ln101_fu_489_p2, "icmp_ln101_fu_489_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln105_fu_506_p2, "icmp_ln105_fu_506_p2");
    sc_trace(mVcdFile, W_q0, "W_q0");
    sc_trace(mVcdFile, W_load_reg_1053, "W_load_reg_1053");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, W_q1, "W_q1");
    sc_trace(mVcdFile, W_load_1_reg_1058, "W_load_1_reg_1058");
    sc_trace(mVcdFile, i_6_fu_578_p2, "i_6_fu_578_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, A_reg_1078, "A_reg_1078");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, B_reg_1084, "B_reg_1084");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, C_reg_1090, "C_reg_1090");
    sc_trace(mVcdFile, D_reg_1096, "D_reg_1096");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, E_reg_1102, "E_reg_1102");
    sc_trace(mVcdFile, i_7_fu_590_p2, "i_7_fu_590_p2");
    sc_trace(mVcdFile, i_7_reg_1111, "i_7_reg_1111");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, icmp_ln115_fu_584_p2, "icmp_ln115_fu_584_p2");
    sc_trace(mVcdFile, temp_fu_665_p2, "temp_fu_665_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, C_1_fu_685_p3, "C_1_fu_685_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, icmp_ln119_fu_693_p2, "icmp_ln119_fu_693_p2");
    sc_trace(mVcdFile, i_8_fu_704_p2, "i_8_fu_704_p2");
    sc_trace(mVcdFile, i_8_reg_1139, "i_8_reg_1139");
    sc_trace(mVcdFile, temp_1_fu_762_p2, "temp_1_fu_762_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, C_2_fu_782_p3, "C_2_fu_782_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, icmp_ln123_fu_790_p2, "icmp_ln123_fu_790_p2");
    sc_trace(mVcdFile, i_9_fu_801_p2, "i_9_fu_801_p2");
    sc_trace(mVcdFile, i_9_reg_1162, "i_9_reg_1162");
    sc_trace(mVcdFile, temp_2_fu_871_p2, "temp_2_fu_871_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, C_3_fu_891_p3, "C_3_fu_891_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, icmp_ln127_fu_899_p2, "icmp_ln127_fu_899_p2");
    sc_trace(mVcdFile, add_ln129_2_fu_950_p2, "add_ln129_2_fu_950_p2");
    sc_trace(mVcdFile, add_ln129_2_reg_1185, "add_ln129_2_reg_1185");
    sc_trace(mVcdFile, C_4_fu_970_p3, "C_4_fu_970_p3");
    sc_trace(mVcdFile, C_4_reg_1190, "C_4_reg_1190");
    sc_trace(mVcdFile, i_10_fu_978_p2, "i_10_fu_978_p2");
    sc_trace(mVcdFile, i_10_reg_1195, "i_10_reg_1195");
    sc_trace(mVcdFile, add_ln134_fu_996_p2, "add_ln134_fu_996_p2");
    sc_trace(mVcdFile, add_ln134_reg_1200, "add_ln134_reg_1200");
    sc_trace(mVcdFile, add_ln135_fu_1001_p2, "add_ln135_fu_1001_p2");
    sc_trace(mVcdFile, add_ln135_reg_1205, "add_ln135_reg_1205");
    sc_trace(mVcdFile, temp_3_fu_1012_p2, "temp_3_fu_1012_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, add_ln136_fu_1017_p2, "add_ln136_fu_1017_p2");
    sc_trace(mVcdFile, add_ln136_reg_1215, "add_ln136_reg_1215");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, W_address0, "W_address0");
    sc_trace(mVcdFile, W_ce0, "W_ce0");
    sc_trace(mVcdFile, W_we0, "W_we0");
    sc_trace(mVcdFile, W_address1, "W_address1");
    sc_trace(mVcdFile, W_ce1, "W_ce1");
    sc_trace(mVcdFile, W_we1, "W_we1");
    sc_trace(mVcdFile, W_d1, "W_d1");
    sc_trace(mVcdFile, i_0_reg_196, "i_0_reg_196");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_1_reg_207, "i_1_reg_207");
    sc_trace(mVcdFile, E_0_reg_219, "E_0_reg_219");
    sc_trace(mVcdFile, E_4_reg_229, "E_4_reg_229");
    sc_trace(mVcdFile, D_1_reg_240, "D_1_reg_240");
    sc_trace(mVcdFile, B_0_reg_251, "B_0_reg_251");
    sc_trace(mVcdFile, B_4_reg_261, "B_4_reg_261");
    sc_trace(mVcdFile, i_2_reg_272, "i_2_reg_272");
    sc_trace(mVcdFile, E_5_reg_294, "E_5_reg_294");
    sc_trace(mVcdFile, E_1_reg_283, "E_1_reg_283");
    sc_trace(mVcdFile, D_2_reg_306, "D_2_reg_306");
    sc_trace(mVcdFile, B_5_reg_329, "B_5_reg_329");
    sc_trace(mVcdFile, B_1_reg_318, "B_1_reg_318");
    sc_trace(mVcdFile, i_3_reg_341, "i_3_reg_341");
    sc_trace(mVcdFile, E_6_reg_363, "E_6_reg_363");
    sc_trace(mVcdFile, E_2_reg_352, "E_2_reg_352");
    sc_trace(mVcdFile, D_3_reg_375, "D_3_reg_375");
    sc_trace(mVcdFile, B_6_reg_398, "B_6_reg_398");
    sc_trace(mVcdFile, B_2_reg_387, "B_2_reg_387");
    sc_trace(mVcdFile, i_4_reg_410, "i_4_reg_410");
    sc_trace(mVcdFile, E_7_reg_432, "E_7_reg_432");
    sc_trace(mVcdFile, E_3_reg_421, "E_3_reg_421");
    sc_trace(mVcdFile, D_4_reg_444, "D_4_reg_444");
    sc_trace(mVcdFile, B_7_reg_466, "B_7_reg_466");
    sc_trace(mVcdFile, B_3_reg_456, "B_3_reg_456");
    sc_trace(mVcdFile, i_5_reg_478, "i_5_reg_478");
    sc_trace(mVcdFile, zext_ln107_fu_518_p1, "zext_ln107_fu_518_p1");
    sc_trace(mVcdFile, zext_ln107_1_fu_529_p1, "zext_ln107_1_fu_529_p1");
    sc_trace(mVcdFile, zext_ln107_2_fu_540_p1, "zext_ln107_2_fu_540_p1");
    sc_trace(mVcdFile, zext_ln107_3_fu_551_p1, "zext_ln107_3_fu_551_p1");
    sc_trace(mVcdFile, zext_ln107_4_fu_573_p1, "zext_ln107_4_fu_573_p1");
    sc_trace(mVcdFile, zext_ln117_fu_596_p1, "zext_ln117_fu_596_p1");
    sc_trace(mVcdFile, zext_ln121_fu_699_p1, "zext_ln121_fu_699_p1");
    sc_trace(mVcdFile, zext_ln125_fu_796_p1, "zext_ln125_fu_796_p1");
    sc_trace(mVcdFile, zext_ln129_fu_939_p1, "zext_ln129_fu_939_p1");
    sc_trace(mVcdFile, add_ln132_fu_984_p2, "add_ln132_fu_984_p2");
    sc_trace(mVcdFile, add_ln133_fu_990_p2, "add_ln133_fu_990_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, add_ln107_fu_512_p2, "add_ln107_fu_512_p2");
    sc_trace(mVcdFile, add_ln107_1_fu_523_p2, "add_ln107_1_fu_523_p2");
    sc_trace(mVcdFile, add_ln107_2_fu_534_p2, "add_ln107_2_fu_534_p2");
    sc_trace(mVcdFile, add_ln107_3_fu_545_p2, "add_ln107_3_fu_545_p2");
    sc_trace(mVcdFile, xor_ln107_1_fu_560_p2, "xor_ln107_1_fu_560_p2");
    sc_trace(mVcdFile, xor_ln107_fu_556_p2, "xor_ln107_fu_556_p2");
    sc_trace(mVcdFile, trunc_ln117_fu_601_p1, "trunc_ln117_fu_601_p1");
    sc_trace(mVcdFile, lshr_ln_fu_605_p4, "lshr_ln_fu_605_p4");
    sc_trace(mVcdFile, xor_ln117_fu_629_p2, "xor_ln117_fu_629_p2");
    sc_trace(mVcdFile, and_ln117_fu_623_p2, "and_ln117_fu_623_p2");
    sc_trace(mVcdFile, and_ln117_1_fu_635_p2, "and_ln117_1_fu_635_p2");
    sc_trace(mVcdFile, or_ln_fu_615_p3, "or_ln_fu_615_p3");
    sc_trace(mVcdFile, add_ln117_1_fu_653_p2, "add_ln117_1_fu_653_p2");
    sc_trace(mVcdFile, or_ln117_fu_641_p2, "or_ln117_fu_641_p2");
    sc_trace(mVcdFile, add_ln117_2_fu_659_p2, "add_ln117_2_fu_659_p2");
    sc_trace(mVcdFile, add_ln117_fu_647_p2, "add_ln117_fu_647_p2");
    sc_trace(mVcdFile, trunc_ln117_1_fu_671_p1, "trunc_ln117_1_fu_671_p1");
    sc_trace(mVcdFile, lshr_ln117_1_fu_675_p4, "lshr_ln117_1_fu_675_p4");
    sc_trace(mVcdFile, trunc_ln121_fu_710_p1, "trunc_ln121_fu_710_p1");
    sc_trace(mVcdFile, lshr_ln1_fu_714_p4, "lshr_ln1_fu_714_p4");
    sc_trace(mVcdFile, xor_ln121_fu_732_p2, "xor_ln121_fu_732_p2");
    sc_trace(mVcdFile, or_ln1_fu_724_p3, "or_ln1_fu_724_p3");
    sc_trace(mVcdFile, add_ln121_1_fu_750_p2, "add_ln121_1_fu_750_p2");
    sc_trace(mVcdFile, xor_ln121_1_fu_738_p2, "xor_ln121_1_fu_738_p2");
    sc_trace(mVcdFile, add_ln121_2_fu_756_p2, "add_ln121_2_fu_756_p2");
    sc_trace(mVcdFile, add_ln121_fu_744_p2, "add_ln121_fu_744_p2");
    sc_trace(mVcdFile, trunc_ln121_1_fu_768_p1, "trunc_ln121_1_fu_768_p1");
    sc_trace(mVcdFile, lshr_ln121_1_fu_772_p4, "lshr_ln121_1_fu_772_p4");
    sc_trace(mVcdFile, trunc_ln125_fu_807_p1, "trunc_ln125_fu_807_p1");
    sc_trace(mVcdFile, lshr_ln2_fu_811_p4, "lshr_ln2_fu_811_p4");
    sc_trace(mVcdFile, or_ln125_fu_829_p2, "or_ln125_fu_829_p2");
    sc_trace(mVcdFile, and_ln125_fu_835_p2, "and_ln125_fu_835_p2");
    sc_trace(mVcdFile, and_ln125_1_fu_841_p2, "and_ln125_1_fu_841_p2");
    sc_trace(mVcdFile, or_ln125_1_fu_847_p2, "or_ln125_1_fu_847_p2");
    sc_trace(mVcdFile, or_ln2_fu_821_p3, "or_ln2_fu_821_p3");
    sc_trace(mVcdFile, add_ln125_1_fu_859_p2, "add_ln125_1_fu_859_p2");
    sc_trace(mVcdFile, add_ln125_2_fu_865_p2, "add_ln125_2_fu_865_p2");
    sc_trace(mVcdFile, add_ln125_fu_853_p2, "add_ln125_fu_853_p2");
    sc_trace(mVcdFile, trunc_ln125_1_fu_877_p1, "trunc_ln125_1_fu_877_p1");
    sc_trace(mVcdFile, lshr_ln125_1_fu_881_p4, "lshr_ln125_1_fu_881_p4");
    sc_trace(mVcdFile, trunc_ln129_fu_905_p1, "trunc_ln129_fu_905_p1");
    sc_trace(mVcdFile, lshr_ln3_fu_909_p4, "lshr_ln3_fu_909_p4");
    sc_trace(mVcdFile, xor_ln129_fu_927_p2, "xor_ln129_fu_927_p2");
    sc_trace(mVcdFile, or_ln3_fu_919_p3, "or_ln3_fu_919_p3");
    sc_trace(mVcdFile, add_ln129_1_fu_944_p2, "add_ln129_1_fu_944_p2");
    sc_trace(mVcdFile, xor_ln129_1_fu_933_p2, "xor_ln129_1_fu_933_p2");
    sc_trace(mVcdFile, trunc_ln129_1_fu_956_p1, "trunc_ln129_1_fu_956_p1");
    sc_trace(mVcdFile, lshr_ln129_1_fu_960_p4, "lshr_ln129_1_fu_960_p4");
    sc_trace(mVcdFile, add_ln129_fu_1006_p2, "add_ln129_fu_1006_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

sha_transform::~sha_transform() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete W_U;
}

void sha_transform::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        B_0_reg_251 = B_4_reg_261.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        B_0_reg_251 = B_reg_1084.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln115_fu_584_p2.read(), ap_const_lv1_1))) {
        B_1_reg_318 = B_0_reg_251.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        B_1_reg_318 = B_5_reg_329.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(icmp_ln119_fu_693_p2.read(), ap_const_lv1_1))) {
        B_2_reg_387 = B_1_reg_318.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        B_2_reg_387 = B_6_reg_398.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(icmp_ln123_fu_790_p2.read(), ap_const_lv1_1))) {
        B_3_reg_456 = B_2_reg_387.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        B_3_reg_456 = B_7_reg_466.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        B_4_reg_261 = temp_fu_665_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        B_4_reg_261 = A_reg_1078.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln115_fu_584_p2.read(), ap_const_lv1_1))) {
        B_5_reg_329 = B_4_reg_261.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        B_5_reg_329 = temp_1_fu_762_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(icmp_ln119_fu_693_p2.read(), ap_const_lv1_1))) {
        B_6_reg_398 = B_5_reg_329.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        B_6_reg_398 = temp_2_fu_871_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(icmp_ln123_fu_790_p2.read(), ap_const_lv1_1))) {
        B_7_reg_466 = B_6_reg_398.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        B_7_reg_466 = temp_3_fu_1012_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        D_1_reg_240 = C_1_fu_685_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        D_1_reg_240 = C_reg_1090.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln115_fu_584_p2.read(), ap_const_lv1_1))) {
        D_2_reg_306 = D_1_reg_240.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        D_2_reg_306 = C_2_fu_782_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(icmp_ln119_fu_693_p2.read(), ap_const_lv1_1))) {
        D_3_reg_375 = D_2_reg_306.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        D_3_reg_375 = C_3_fu_891_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(icmp_ln123_fu_790_p2.read(), ap_const_lv1_1))) {
        D_4_reg_444 = D_3_reg_375.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        D_4_reg_444 = C_4_reg_1190.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        E_0_reg_219 = E_4_reg_229.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        E_0_reg_219 = sha_info_digest_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln115_fu_584_p2.read(), ap_const_lv1_1))) {
        E_1_reg_283 = E_0_reg_219.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        E_1_reg_283 = E_5_reg_294.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(icmp_ln119_fu_693_p2.read(), ap_const_lv1_1))) {
        E_2_reg_352 = E_1_reg_283.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        E_2_reg_352 = E_6_reg_363.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(icmp_ln123_fu_790_p2.read(), ap_const_lv1_1))) {
        E_3_reg_421 = E_2_reg_352.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        E_3_reg_421 = E_7_reg_432.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        E_4_reg_229 = D_1_reg_240.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        E_4_reg_229 = sha_info_digest_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln115_fu_584_p2.read(), ap_const_lv1_1))) {
        E_5_reg_294 = E_4_reg_229.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        E_5_reg_294 = D_2_reg_306.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(icmp_ln119_fu_693_p2.read(), ap_const_lv1_1))) {
        E_6_reg_363 = E_5_reg_294.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        E_6_reg_363 = D_3_reg_375.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(icmp_ln123_fu_790_p2.read(), ap_const_lv1_1))) {
        E_7_reg_432 = E_6_reg_363.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        E_7_reg_432 = D_4_reg_444.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_0_reg_196 = i_reg_1025.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_196 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln101_fu_489_p2.read(), ap_const_lv1_1))) {
        i_1_reg_207 = ap_const_lv7_10;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_1_reg_207 = i_6_fu_578_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_2_reg_272 = i_7_reg_1111.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_2_reg_272 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln115_fu_584_p2.read(), ap_const_lv1_1))) {
        i_3_reg_341 = ap_const_lv6_14;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        i_3_reg_341 = i_8_reg_1139.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(icmp_ln119_fu_693_p2.read(), ap_const_lv1_1))) {
        i_4_reg_410 = ap_const_lv6_28;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        i_4_reg_410 = i_9_reg_1162.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(icmp_ln123_fu_790_p2.read(), ap_const_lv1_1))) {
        i_5_reg_478 = ap_const_lv7_3C;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        i_5_reg_478 = i_10_reg_1195.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        A_reg_1078 = sha_info_digest_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        B_reg_1084 = sha_info_digest_q0.read();
        C_reg_1090 = sha_info_digest_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln127_fu_899_p2.read()))) {
        C_4_reg_1190 = C_4_fu_970_p3.read();
        add_ln129_2_reg_1185 = add_ln129_2_fu_950_p2.read();
        i_10_reg_1195 = i_10_fu_978_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        D_reg_1096 = sha_info_digest_q1.read();
        E_reg_1102 = sha_info_digest_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        W_load_1_reg_1058 = W_q1.read();
        W_load_reg_1053 = W_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(icmp_ln127_fu_899_p2.read(), ap_const_lv1_1))) {
        add_ln134_reg_1200 = add_ln134_fu_996_p2.read();
        add_ln135_reg_1205 = add_ln135_fu_1001_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        add_ln136_reg_1215 = add_ln136_fu_1017_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_7_reg_1111 = i_7_fu_590_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln119_fu_693_p2.read()))) {
        i_8_reg_1139 = i_8_fu_704_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln123_fu_790_p2.read()))) {
        i_9_reg_1162 = i_9_fu_801_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_1025 = i_fu_495_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln101_fu_489_p2.read(), ap_const_lv1_0))) {
        zext_ln103_reg_1030 = zext_ln103_fu_501_p1.read();
    }
}

void sha_transform::thread_C_1_fu_685_p3() {
    C_1_fu_685_p3 = esl_concat<2,30>(trunc_ln117_1_fu_671_p1.read(), lshr_ln117_1_fu_675_p4.read());
}

void sha_transform::thread_C_2_fu_782_p3() {
    C_2_fu_782_p3 = esl_concat<2,30>(trunc_ln121_1_fu_768_p1.read(), lshr_ln121_1_fu_772_p4.read());
}

void sha_transform::thread_C_3_fu_891_p3() {
    C_3_fu_891_p3 = esl_concat<2,30>(trunc_ln125_1_fu_877_p1.read(), lshr_ln125_1_fu_881_p4.read());
}

void sha_transform::thread_C_4_fu_970_p3() {
    C_4_fu_970_p3 = esl_concat<2,30>(trunc_ln129_1_fu_956_p1.read(), lshr_ln129_1_fu_960_p4.read());
}

void sha_transform::thread_W_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        W_address0 =  (sc_lv<7>) (zext_ln125_fu_796_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        W_address0 =  (sc_lv<7>) (zext_ln117_fu_596_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        W_address0 =  (sc_lv<7>) (zext_ln107_3_fu_551_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        W_address0 =  (sc_lv<7>) (zext_ln107_fu_518_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        W_address0 =  (sc_lv<7>) (zext_ln103_reg_1030.read());
    } else {
        W_address0 = "XXXXXXX";
    }
}

void sha_transform::thread_W_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        W_address1 =  (sc_lv<7>) (zext_ln129_fu_939_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        W_address1 =  (sc_lv<7>) (zext_ln121_fu_699_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        W_address1 =  (sc_lv<7>) (zext_ln107_4_fu_573_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        W_address1 =  (sc_lv<7>) (zext_ln107_2_fu_540_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        W_address1 =  (sc_lv<7>) (zext_ln107_1_fu_529_p1.read());
    } else {
        W_address1 = "XXXXXXX";
    }
}

void sha_transform::thread_W_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        W_ce0 = ap_const_logic_1;
    } else {
        W_ce0 = ap_const_logic_0;
    }
}

void sha_transform::thread_W_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        W_ce1 = ap_const_logic_1;
    } else {
        W_ce1 = ap_const_logic_0;
    }
}

void sha_transform::thread_W_d1() {
    W_d1 = (xor_ln107_1_fu_560_p2.read() ^ xor_ln107_fu_556_p2.read());
}

void sha_transform::thread_W_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        W_we0 = ap_const_logic_1;
    } else {
        W_we0 = ap_const_logic_0;
    }
}

void sha_transform::thread_W_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        W_we1 = ap_const_logic_1;
    } else {
        W_we1 = ap_const_logic_0;
    }
}

void sha_transform::thread_add_ln107_1_fu_523_p2() {
    add_ln107_1_fu_523_p2 = (!i_1_reg_207.read().is_01() || !ap_const_lv7_78.is_01())? sc_lv<7>(): (sc_biguint<7>(i_1_reg_207.read()) + sc_bigint<7>(ap_const_lv7_78));
}

void sha_transform::thread_add_ln107_2_fu_534_p2() {
    add_ln107_2_fu_534_p2 = (!i_1_reg_207.read().is_01() || !ap_const_lv7_72.is_01())? sc_lv<7>(): (sc_biguint<7>(i_1_reg_207.read()) + sc_bigint<7>(ap_const_lv7_72));
}

void sha_transform::thread_add_ln107_3_fu_545_p2() {
    add_ln107_3_fu_545_p2 = (!i_1_reg_207.read().is_01() || !ap_const_lv7_70.is_01())? sc_lv<7>(): (sc_biguint<7>(i_1_reg_207.read()) + sc_bigint<7>(ap_const_lv7_70));
}

void sha_transform::thread_add_ln107_fu_512_p2() {
    add_ln107_fu_512_p2 = (!i_1_reg_207.read().is_01() || !ap_const_lv7_7D.is_01())? sc_lv<7>(): (sc_biguint<7>(i_1_reg_207.read()) + sc_bigint<7>(ap_const_lv7_7D));
}

void sha_transform::thread_add_ln117_1_fu_653_p2() {
    add_ln117_1_fu_653_p2 = (!ap_const_lv32_5A827999.is_01() || !or_ln_fu_615_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_5A827999) + sc_biguint<32>(or_ln_fu_615_p3.read()));
}

void sha_transform::thread_add_ln117_2_fu_659_p2() {
    add_ln117_2_fu_659_p2 = (!add_ln117_1_fu_653_p2.read().is_01() || !or_ln117_fu_641_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln117_1_fu_653_p2.read()) + sc_biguint<32>(or_ln117_fu_641_p2.read()));
}

void sha_transform::thread_add_ln117_fu_647_p2() {
    add_ln117_fu_647_p2 = (!W_q0.read().is_01() || !E_0_reg_219.read().is_01())? sc_lv<32>(): (sc_biguint<32>(W_q0.read()) + sc_biguint<32>(E_0_reg_219.read()));
}

void sha_transform::thread_add_ln121_1_fu_750_p2() {
    add_ln121_1_fu_750_p2 = (!ap_const_lv32_6ED9EBA1.is_01() || !or_ln1_fu_724_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_6ED9EBA1) + sc_biguint<32>(or_ln1_fu_724_p3.read()));
}

void sha_transform::thread_add_ln121_2_fu_756_p2() {
    add_ln121_2_fu_756_p2 = (!add_ln121_1_fu_750_p2.read().is_01() || !xor_ln121_1_fu_738_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln121_1_fu_750_p2.read()) + sc_biguint<32>(xor_ln121_1_fu_738_p2.read()));
}

void sha_transform::thread_add_ln121_fu_744_p2() {
    add_ln121_fu_744_p2 = (!W_q1.read().is_01() || !E_1_reg_283.read().is_01())? sc_lv<32>(): (sc_biguint<32>(W_q1.read()) + sc_biguint<32>(E_1_reg_283.read()));
}

void sha_transform::thread_add_ln125_1_fu_859_p2() {
    add_ln125_1_fu_859_p2 = (!or_ln125_1_fu_847_p2.read().is_01() || !or_ln2_fu_821_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(or_ln125_1_fu_847_p2.read()) + sc_biguint<32>(or_ln2_fu_821_p3.read()));
}

void sha_transform::thread_add_ln125_2_fu_865_p2() {
    add_ln125_2_fu_865_p2 = (!ap_const_lv32_8F1BBCDC.is_01() || !add_ln125_1_fu_859_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_8F1BBCDC) + sc_biguint<32>(add_ln125_1_fu_859_p2.read()));
}

void sha_transform::thread_add_ln125_fu_853_p2() {
    add_ln125_fu_853_p2 = (!W_q0.read().is_01() || !E_2_reg_352.read().is_01())? sc_lv<32>(): (sc_biguint<32>(W_q0.read()) + sc_biguint<32>(E_2_reg_352.read()));
}

void sha_transform::thread_add_ln129_1_fu_944_p2() {
    add_ln129_1_fu_944_p2 = (!ap_const_lv32_CA62C1D6.is_01() || !or_ln3_fu_919_p3.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_CA62C1D6) + sc_biguint<32>(or_ln3_fu_919_p3.read()));
}

void sha_transform::thread_add_ln129_2_fu_950_p2() {
    add_ln129_2_fu_950_p2 = (!add_ln129_1_fu_944_p2.read().is_01() || !xor_ln129_1_fu_933_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln129_1_fu_944_p2.read()) + sc_biguint<32>(xor_ln129_1_fu_933_p2.read()));
}

void sha_transform::thread_add_ln129_fu_1006_p2() {
    add_ln129_fu_1006_p2 = (!W_q1.read().is_01() || !E_3_reg_421.read().is_01())? sc_lv<32>(): (sc_biguint<32>(W_q1.read()) + sc_biguint<32>(E_3_reg_421.read()));
}

void sha_transform::thread_add_ln132_fu_984_p2() {
    add_ln132_fu_984_p2 = (!A_reg_1078.read().is_01() || !B_7_reg_466.read().is_01())? sc_lv<32>(): (sc_biguint<32>(A_reg_1078.read()) + sc_biguint<32>(B_7_reg_466.read()));
}

void sha_transform::thread_add_ln133_fu_990_p2() {
    add_ln133_fu_990_p2 = (!B_reg_1084.read().is_01() || !B_3_reg_456.read().is_01())? sc_lv<32>(): (sc_biguint<32>(B_reg_1084.read()) + sc_biguint<32>(B_3_reg_456.read()));
}

void sha_transform::thread_add_ln134_fu_996_p2() {
    add_ln134_fu_996_p2 = (!C_reg_1090.read().is_01() || !D_4_reg_444.read().is_01())? sc_lv<32>(): (sc_biguint<32>(C_reg_1090.read()) + sc_biguint<32>(D_4_reg_444.read()));
}

void sha_transform::thread_add_ln135_fu_1001_p2() {
    add_ln135_fu_1001_p2 = (!D_reg_1096.read().is_01() || !E_7_reg_432.read().is_01())? sc_lv<32>(): (sc_biguint<32>(D_reg_1096.read()) + sc_biguint<32>(E_7_reg_432.read()));
}

void sha_transform::thread_add_ln136_fu_1017_p2() {
    add_ln136_fu_1017_p2 = (!E_reg_1102.read().is_01() || !E_3_reg_421.read().is_01())? sc_lv<32>(): (sc_biguint<32>(E_reg_1102.read()) + sc_biguint<32>(E_3_reg_421.read()));
}

void sha_transform::thread_and_ln117_1_fu_635_p2() {
    and_ln117_1_fu_635_p2 = (E_4_reg_229.read() & xor_ln117_fu_629_p2.read());
}

void sha_transform::thread_and_ln117_fu_623_p2() {
    and_ln117_fu_623_p2 = (B_0_reg_251.read() & D_1_reg_240.read());
}

void sha_transform::thread_and_ln125_1_fu_841_p2() {
    and_ln125_1_fu_841_p2 = (D_3_reg_375.read() & E_6_reg_363.read());
}

void sha_transform::thread_and_ln125_fu_835_p2() {
    and_ln125_fu_835_p2 = (B_2_reg_387.read() & or_ln125_fu_829_p2.read());
}

void sha_transform::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void sha_transform::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void sha_transform::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void sha_transform::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void sha_transform::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void sha_transform::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void sha_transform::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void sha_transform::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void sha_transform::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void sha_transform::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void sha_transform::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void sha_transform::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void sha_transform::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void sha_transform::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void sha_transform::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void sha_transform::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void sha_transform::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void sha_transform::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void sha_transform::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void sha_transform::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sha_transform::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sha_transform::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sha_transform::thread_i_10_fu_978_p2() {
    i_10_fu_978_p2 = (!ap_const_lv7_1.is_01() || !i_5_reg_478.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(i_5_reg_478.read()));
}

void sha_transform::thread_i_6_fu_578_p2() {
    i_6_fu_578_p2 = (!i_1_reg_207.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_1_reg_207.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void sha_transform::thread_i_7_fu_590_p2() {
    i_7_fu_590_p2 = (!i_2_reg_272.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_2_reg_272.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void sha_transform::thread_i_8_fu_704_p2() {
    i_8_fu_704_p2 = (!ap_const_lv6_1.is_01() || !i_3_reg_341.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(i_3_reg_341.read()));
}

void sha_transform::thread_i_9_fu_801_p2() {
    i_9_fu_801_p2 = (!ap_const_lv6_1.is_01() || !i_4_reg_410.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(i_4_reg_410.read()));
}

void sha_transform::thread_i_fu_495_p2() {
    i_fu_495_p2 = (!i_0_reg_196.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_reg_196.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void sha_transform::thread_icmp_ln101_fu_489_p2() {
    icmp_ln101_fu_489_p2 = (!i_0_reg_196.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_196.read() == ap_const_lv5_10);
}

void sha_transform::thread_icmp_ln105_fu_506_p2() {
    icmp_ln105_fu_506_p2 = (!i_1_reg_207.read().is_01() || !ap_const_lv7_50.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_207.read() == ap_const_lv7_50);
}

void sha_transform::thread_icmp_ln115_fu_584_p2() {
    icmp_ln115_fu_584_p2 = (!i_2_reg_272.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_272.read() == ap_const_lv5_14);
}

void sha_transform::thread_icmp_ln119_fu_693_p2() {
    icmp_ln119_fu_693_p2 = (!i_3_reg_341.read().is_01() || !ap_const_lv6_28.is_01())? sc_lv<1>(): sc_lv<1>(i_3_reg_341.read() == ap_const_lv6_28);
}

void sha_transform::thread_icmp_ln123_fu_790_p2() {
    icmp_ln123_fu_790_p2 = (!i_4_reg_410.read().is_01() || !ap_const_lv6_3C.is_01())? sc_lv<1>(): sc_lv<1>(i_4_reg_410.read() == ap_const_lv6_3C);
}

void sha_transform::thread_icmp_ln127_fu_899_p2() {
    icmp_ln127_fu_899_p2 = (!i_5_reg_478.read().is_01() || !ap_const_lv7_50.is_01())? sc_lv<1>(): sc_lv<1>(i_5_reg_478.read() == ap_const_lv7_50);
}

void sha_transform::thread_lshr_ln117_1_fu_675_p4() {
    lshr_ln117_1_fu_675_p4 = B_0_reg_251.read().range(31, 2);
}

void sha_transform::thread_lshr_ln121_1_fu_772_p4() {
    lshr_ln121_1_fu_772_p4 = B_1_reg_318.read().range(31, 2);
}

void sha_transform::thread_lshr_ln125_1_fu_881_p4() {
    lshr_ln125_1_fu_881_p4 = B_2_reg_387.read().range(31, 2);
}

void sha_transform::thread_lshr_ln129_1_fu_960_p4() {
    lshr_ln129_1_fu_960_p4 = B_3_reg_456.read().range(31, 2);
}

void sha_transform::thread_lshr_ln1_fu_714_p4() {
    lshr_ln1_fu_714_p4 = B_5_reg_329.read().range(31, 27);
}

void sha_transform::thread_lshr_ln2_fu_811_p4() {
    lshr_ln2_fu_811_p4 = B_6_reg_398.read().range(31, 27);
}

void sha_transform::thread_lshr_ln3_fu_909_p4() {
    lshr_ln3_fu_909_p4 = B_7_reg_466.read().range(31, 27);
}

void sha_transform::thread_lshr_ln_fu_605_p4() {
    lshr_ln_fu_605_p4 = B_4_reg_261.read().range(31, 27);
}

void sha_transform::thread_or_ln117_fu_641_p2() {
    or_ln117_fu_641_p2 = (and_ln117_fu_623_p2.read() | and_ln117_1_fu_635_p2.read());
}

void sha_transform::thread_or_ln125_1_fu_847_p2() {
    or_ln125_1_fu_847_p2 = (and_ln125_fu_835_p2.read() | and_ln125_1_fu_841_p2.read());
}

void sha_transform::thread_or_ln125_fu_829_p2() {
    or_ln125_fu_829_p2 = (D_3_reg_375.read() | E_6_reg_363.read());
}

void sha_transform::thread_or_ln1_fu_724_p3() {
    or_ln1_fu_724_p3 = esl_concat<27,5>(trunc_ln121_fu_710_p1.read(), lshr_ln1_fu_714_p4.read());
}

void sha_transform::thread_or_ln2_fu_821_p3() {
    or_ln2_fu_821_p3 = esl_concat<27,5>(trunc_ln125_fu_807_p1.read(), lshr_ln2_fu_811_p4.read());
}

void sha_transform::thread_or_ln3_fu_919_p3() {
    or_ln3_fu_919_p3 = esl_concat<27,5>(trunc_ln129_fu_905_p1.read(), lshr_ln3_fu_909_p4.read());
}

void sha_transform::thread_or_ln_fu_615_p3() {
    or_ln_fu_615_p3 = esl_concat<27,5>(trunc_ln117_fu_601_p1.read(), lshr_ln_fu_605_p4.read());
}

void sha_transform::thread_sha_info_data_address0() {
    sha_info_data_address0 =  (sc_lv<4>) (zext_ln103_fu_501_p1.read());
}

void sha_transform::thread_sha_info_data_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        sha_info_data_ce0 = ap_const_logic_1;
    } else {
        sha_info_data_ce0 = ap_const_logic_0;
    }
}

void sha_transform::thread_sha_info_digest_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        sha_info_digest_address0 = ap_const_lv3_3;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sha_info_digest_address0 = ap_const_lv3_4;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        sha_info_digest_address0 = ap_const_lv3_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sha_info_digest_address0 = ap_const_lv3_0;
    } else {
        sha_info_digest_address0 =  (sc_lv<3>) ("XXX");
    }
}

void sha_transform::thread_sha_info_digest_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        sha_info_digest_address1 = ap_const_lv3_4;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        sha_info_digest_address1 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sha_info_digest_address1 = ap_const_lv3_3;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        sha_info_digest_address1 = ap_const_lv3_2;
    } else {
        sha_info_digest_address1 =  (sc_lv<3>) ("XXX");
    }
}

void sha_transform::thread_sha_info_digest_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        sha_info_digest_ce0 = ap_const_logic_1;
    } else {
        sha_info_digest_ce0 = ap_const_logic_0;
    }
}

void sha_transform::thread_sha_info_digest_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        sha_info_digest_ce1 = ap_const_logic_1;
    } else {
        sha_info_digest_ce1 = ap_const_logic_0;
    }
}

void sha_transform::thread_sha_info_digest_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        sha_info_digest_d0 = add_ln135_reg_1205.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        sha_info_digest_d0 = add_ln133_fu_990_p2.read();
    } else {
        sha_info_digest_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void sha_transform::thread_sha_info_digest_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        sha_info_digest_d1 = add_ln136_reg_1215.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        sha_info_digest_d1 = add_ln134_reg_1200.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        sha_info_digest_d1 = add_ln132_fu_984_p2.read();
    } else {
        sha_info_digest_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void sha_transform::thread_sha_info_digest_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
          esl_seteq<1,1,1>(icmp_ln127_fu_899_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        sha_info_digest_we0 = ap_const_logic_1;
    } else {
        sha_info_digest_we0 = ap_const_logic_0;
    }
}

void sha_transform::thread_sha_info_digest_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
          esl_seteq<1,1,1>(icmp_ln127_fu_899_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        sha_info_digest_we1 = ap_const_logic_1;
    } else {
        sha_info_digest_we1 = ap_const_logic_0;
    }
}

void sha_transform::thread_temp_1_fu_762_p2() {
    temp_1_fu_762_p2 = (!add_ln121_2_fu_756_p2.read().is_01() || !add_ln121_fu_744_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln121_2_fu_756_p2.read()) + sc_biguint<32>(add_ln121_fu_744_p2.read()));
}

void sha_transform::thread_temp_2_fu_871_p2() {
    temp_2_fu_871_p2 = (!add_ln125_2_fu_865_p2.read().is_01() || !add_ln125_fu_853_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln125_2_fu_865_p2.read()) + sc_biguint<32>(add_ln125_fu_853_p2.read()));
}

void sha_transform::thread_temp_3_fu_1012_p2() {
    temp_3_fu_1012_p2 = (!add_ln129_2_reg_1185.read().is_01() || !add_ln129_fu_1006_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln129_2_reg_1185.read()) + sc_biguint<32>(add_ln129_fu_1006_p2.read()));
}

void sha_transform::thread_temp_fu_665_p2() {
    temp_fu_665_p2 = (!add_ln117_2_fu_659_p2.read().is_01() || !add_ln117_fu_647_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln117_2_fu_659_p2.read()) + sc_biguint<32>(add_ln117_fu_647_p2.read()));
}

void sha_transform::thread_trunc_ln117_1_fu_671_p1() {
    trunc_ln117_1_fu_671_p1 = B_0_reg_251.read().range(2-1, 0);
}

void sha_transform::thread_trunc_ln117_fu_601_p1() {
    trunc_ln117_fu_601_p1 = B_4_reg_261.read().range(27-1, 0);
}

void sha_transform::thread_trunc_ln121_1_fu_768_p1() {
    trunc_ln121_1_fu_768_p1 = B_1_reg_318.read().range(2-1, 0);
}

void sha_transform::thread_trunc_ln121_fu_710_p1() {
    trunc_ln121_fu_710_p1 = B_5_reg_329.read().range(27-1, 0);
}

void sha_transform::thread_trunc_ln125_1_fu_877_p1() {
    trunc_ln125_1_fu_877_p1 = B_2_reg_387.read().range(2-1, 0);
}

void sha_transform::thread_trunc_ln125_fu_807_p1() {
    trunc_ln125_fu_807_p1 = B_6_reg_398.read().range(27-1, 0);
}

void sha_transform::thread_trunc_ln129_1_fu_956_p1() {
    trunc_ln129_1_fu_956_p1 = B_3_reg_456.read().range(2-1, 0);
}

void sha_transform::thread_trunc_ln129_fu_905_p1() {
    trunc_ln129_fu_905_p1 = B_7_reg_466.read().range(27-1, 0);
}

void sha_transform::thread_xor_ln107_1_fu_560_p2() {
    xor_ln107_1_fu_560_p2 = (W_q1.read() ^ W_q0.read());
}

void sha_transform::thread_xor_ln107_fu_556_p2() {
    xor_ln107_fu_556_p2 = (W_load_1_reg_1058.read() ^ W_load_reg_1053.read());
}

void sha_transform::thread_xor_ln117_fu_629_p2() {
    xor_ln117_fu_629_p2 = (B_0_reg_251.read() ^ ap_const_lv32_FFFFFFFF);
}

void sha_transform::thread_xor_ln121_1_fu_738_p2() {
    xor_ln121_1_fu_738_p2 = (xor_ln121_fu_732_p2.read() ^ D_2_reg_306.read());
}

void sha_transform::thread_xor_ln121_fu_732_p2() {
    xor_ln121_fu_732_p2 = (E_5_reg_294.read() ^ B_1_reg_318.read());
}

void sha_transform::thread_xor_ln129_1_fu_933_p2() {
    xor_ln129_1_fu_933_p2 = (xor_ln129_fu_927_p2.read() ^ D_4_reg_444.read());
}

void sha_transform::thread_xor_ln129_fu_927_p2() {
    xor_ln129_fu_927_p2 = (E_7_reg_432.read() ^ B_3_reg_456.read());
}

void sha_transform::thread_zext_ln103_fu_501_p1() {
    zext_ln103_fu_501_p1 = esl_zext<64,5>(i_0_reg_196.read());
}

void sha_transform::thread_zext_ln107_1_fu_529_p1() {
    zext_ln107_1_fu_529_p1 = esl_zext<64,7>(add_ln107_1_fu_523_p2.read());
}

void sha_transform::thread_zext_ln107_2_fu_540_p1() {
    zext_ln107_2_fu_540_p1 = esl_zext<64,7>(add_ln107_2_fu_534_p2.read());
}

void sha_transform::thread_zext_ln107_3_fu_551_p1() {
    zext_ln107_3_fu_551_p1 = esl_zext<64,7>(add_ln107_3_fu_545_p2.read());
}

void sha_transform::thread_zext_ln107_4_fu_573_p1() {
    zext_ln107_4_fu_573_p1 = esl_zext<64,7>(i_1_reg_207.read());
}

void sha_transform::thread_zext_ln107_fu_518_p1() {
    zext_ln107_fu_518_p1 = esl_zext<64,7>(add_ln107_fu_512_p2.read());
}

void sha_transform::thread_zext_ln117_fu_596_p1() {
    zext_ln117_fu_596_p1 = esl_zext<64,5>(i_2_reg_272.read());
}

void sha_transform::thread_zext_ln121_fu_699_p1() {
    zext_ln121_fu_699_p1 = esl_zext<64,6>(i_3_reg_341.read());
}

void sha_transform::thread_zext_ln125_fu_796_p1() {
    zext_ln125_fu_796_p1 = esl_zext<64,6>(i_4_reg_410.read());
}

void sha_transform::thread_zext_ln129_fu_939_p1() {
    zext_ln129_fu_939_p1 = esl_zext<64,7>(i_5_reg_478.read());
}

void sha_transform::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln101_fu_489_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln105_fu_506_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(icmp_ln115_fu_584_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(icmp_ln119_fu_693_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(icmp_ln123_fu_790_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state16;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(icmp_ln127_fu_899_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<19>) ("XXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

